external backup now supports multi config

diff --git a/linux/snapshot b/linux/snapshot
--- a/linux/snapshot
+++ b/linux/snapshot
@@ -39,13 +39,13 @@ snapls() {
 }
 
 snapshot() {
-    snapname=$1
-    snaproot=$2
-    snapdest=$3
-    [[ ! -d "${snapdest}" ]] && mkdir "${snapdest}"
-    btrfs subv snapshot -r \
-        "${snaproot}" \
-        "${snapdest}/${snapname}-$(fdate)"
+    [[ ! -d "${LOCAL_SNAPSHOT_MOUNT}" ]] && mkdir "${LOCAL_SNAPSHOT_MOUNT}"
+    if [[ -z "$noop" ]]
+    then
+        btrfs subv snapshot -r \
+            "${SUBVOLUME}" \
+            "${LOCAL_SNAPSHOT_MOUNT}/${config}-$(fdate)"
+    fi
 }
 
 is_snapshot_in_24_hrs() {
@@ -140,8 +140,11 @@ remove_snapshots() {
     ROOT=$1
     while IFS= read -r snapshot
     do
-        #echo "Removing ${ROOT}/$snapshot"
-        btrfs subvol delete "${ROOT}/$snapshot"
+        echo "Removing ${ROOT}/$snapshot"
+        if [[ -z "$noop" ]]
+        then
+            btrfs subvol delete "${ROOT}/$snapshot"
+        fi
     done
 }
 
@@ -158,15 +161,13 @@ prune() {
     # step 6. build list of number of snapshots needed to delete to meet threshold
     # step 7. delete list of snapshots
     # step 6. delete oldest to
-    vol=$1
-    ROOT=$2
-    snaps_to_keep=$(get_keep_snapshots "$vol" $ROOT)
-    prune_list="$(invert_list "$snaps_to_keep" "$vol" "$ROOT")"
+    snaps_to_keep=$(get_keep_snapshots "$config" $LOCAL_SNAPSHOT_MOUNT)
+    prune_list="$(invert_list "$snaps_to_keep" "$config" "$LOCAL_SNAPSHOT_MOUNT")"
     num_to_prune=$(num_of_snaps "$prune_list")
     [ "$num_to_prune" -eq 0 ] && return
-    echo "keep $(num_of_snaps "$snaps_to_keep") $vol snaps on $ROOT"
-    echo "prune $num_to_prune $vol snaps on $ROOT"
-    echo "$prune_list" | remove_snapshots "$ROOT"
+    echo "keep $(num_of_snaps "$snaps_to_keep") $config snaps on $LOCAL_SNAPSHOT_MOUNT"
+    echo "prune $num_to_prune $config snaps on $LOCAL_SNAPSHOT_MOUNT"
+    echo "$prune_list" | remove_snapshots "$LOCAL_SNAPSHOT_MOUNT"
 }
 
 num_of_snaps(){
@@ -214,20 +215,26 @@ send(){
         if [[ -n $parent ]]
         then
             echo "backup $i with parent $parent"
-            btrfs send -p "${LOCAL_SNAPSHOT_MOUNT}/$parent" \
-                "${LOCAL_SNAPSHOT_MOUNT}/$i" |
-                btrfs receive "${EXTERN_SNAPSHOT_MOUNT}"
-            if [ $? != 0 ]; then
-                echo "An error occurred. Halting."
-                exit 1
+            if [[ -z "$noop" ]]
+            then
+                btrfs send -p "${LOCAL_SNAPSHOT_MOUNT}/$parent" \
+                    "${LOCAL_SNAPSHOT_MOUNT}/$i" |
+                    btrfs receive "${EXTERN_SNAPSHOT_MOUNT}"
+                if [ $? != 0 ]; then
+                    echo "An error occurred. Halting."
+                    exit 1
+                fi
             fi
         else
             echo "full backup $i"
-            btrfs send "${LOCAL_SNAPSHOT_MOUNT}/$i" |
-                btrfs receive "${EXTERN_SNAPSHOT_MOUNT}"
-            if [ $? != 0 ]; then
-                echo "An error occurred. Halting."
-                exit 1
+            if [[ -z "$noop" ]]
+            then
+                btrfs send "${LOCAL_SNAPSHOT_MOUNT}/$i" |
+                    btrfs receive "${EXTERN_SNAPSHOT_MOUNT}"
+                if [ $? != 0 ]; then
+                    echo "An error occurred. Halting."
+                    exit 1
+                fi
             fi
         fi
         parent=$i
@@ -240,10 +247,13 @@ prune_but_keep_some(){
     new_list=$(echo "$list"|head -n -2)
     for i in $new_list; do
         echo "removing $i"
-        btrfs subvol delete "${LOCAL_SNAPSHOT_MOUNT}/$i"
-        if [ $? != 0 ]; then
-            echo "An error occurred. Halting"
-            exit 1
+        if [[ -z "$noop" ]]
+        then
+            btrfs subvol delete "${LOCAL_SNAPSHOT_MOUNT}/$i"
+            if [ $? != 0 ]; then
+                echo "An error occurred. Halting"
+                exit 1
+            fi
         fi
     done
 }
@@ -255,35 +265,38 @@ backup_snapshots(){
     #    sequence is.
     # 4. Foreach one, send it across and once it is send
     #    delete it locally except the last one.
-    while IFS= read -r vol
-    do
-        vol="${vol#@}"
-        all_extern_snaps=$(snapls "${vol}" "${EXTERN_SNAPSHOT_MOUNT}")
-        all_intern_snaps=$(snapls "${vol}" "${LOCAL_SNAPSHOT_MOUNT}")
-        num_of_extern_snaps=$(num_of_snaps "$all_extern_snaps")
-        num_of_intern_snaps=$(num_of_snaps "$all_intern_snaps")
-        echo "there are $num_of_intern_snaps snapshots of $vol"
-        [ "$num_of_intern_snaps" == 0 ] && 
-            echo "skipping $vol" && continue
-        # get a list of snapshots that don't exist on intern yet
-        # get a list of snapshots that exist on both
-        only_intern=$(only_in_a "$all_intern_snaps" "$all_extern_snaps")
-        num_only_intern=$(num_of_snaps "$only_intern")
-        [ "$num_only_intern" == 0 ] &&
-            echo "none to send for $vol" && continue
-        intern_and_extern=$(a_and_b "$all_intern_snaps" "$all_extern_snaps")
-        echo "need to send over $num_only_intern"
-        send "$only_intern" "$intern_and_extern" || exit 1
-        prune_but_keep_some "$all_intern_snaps" || exit 1
-    done
+    all_extern_snaps=$(snapls "${config}" "${EXTERN_SNAPSHOT_MOUNT}")
+    all_intern_snaps=$(snapls "${config}" "${LOCAL_SNAPSHOT_MOUNT}")
+    num_of_extern_snaps=$(num_of_snaps "$all_extern_snaps")
+    num_of_intern_snaps=$(num_of_snaps "$all_intern_snaps")
+    echo "there are $num_of_intern_snaps snapshots of $config"
+    [ "$num_of_intern_snaps" == 0 ] && 
+        echo "skipping $config" && continue
+    # get a list of snapshots that don't exist on intern yet
+    # get a list of snapshots that exist on both
+    only_intern=$(only_in_a "$all_intern_snaps" "$all_extern_snaps")
+    num_only_intern=$(num_of_snaps "$only_intern")
+    [ "$num_only_intern" == 0 ] &&
+        echo "none to send for $config" && continue
+    intern_and_extern=$(a_and_b "$all_intern_snaps" "$all_extern_snaps")
+    echo "need to send over $num_only_intern"
+    send "$only_intern" "$intern_and_extern" || exit 1
+    prune_but_keep_some "$all_intern_snaps" || exit 1
 }
 
-attempt_extern_backup(){
+attempt_extern_backup() {
+    [[ "$backup" == "false" ]] && return 0
     if [[ -d "${EXTERN_SNAPSHOT_MOUNT}" ]]
     then
-        echo "attempting to backup to external disk"
-        echo "$SUBVOLUMES" | backup_snapshots
-        echo "$SUBVOLUMES" | prune "${EXTERN_SNAPSHOT_MOUNT}"
+        if test_running_send
+        then
+            echo "Backup already in progress"
+        else
+            echo "attempting to backup to external disk"
+            # backup_snapshots "$SUBVOLUME" 
+            backup_snapshots $config
+            #prune "${EXTERN_SNAPSHOT_MOUNT}"
+        fi
     else
         echo "${EXTERN_SNAPSHOT_MOUNT} not mounted"
     fi
@@ -337,35 +350,28 @@ get_config() {
 
 }
 
-#get_config count
-#get_config BtrfsRoot root
-#get_config list
+while test $# -gt 0
+do
+    case "$1" in
+        -b|--backup-only)   backup="true";shift;;
+        -n|--dry-run)       noop="true";shift;;
+        -d|--dont-backup)   backup="false";shift;;
+        *)                  break;;
+    esac
+done
 
-# get volumes to snapshot
 for config in $(get_config list); do
     echo "Snapshotting $config"
-    VOLUME_ROOT_MOUNT=$(get_config BtrfsRoot $config) || exit 1
     LOCAL_SNAPSHOT_MOUNT=$(get_config LocalSnapshots $config) || exit 1
     EXTERN_SNAPSHOT_MOUNT=$(get_config RemoteSnapshots $config) || exit 1 
     SUBVOLUME=$(get_config SubvolumeRoot $config) || exit 1
-    if [[ "$1" == "-b" ]]
+    if [[ "$backup" == "true" ]]
     then
-        if [[ test_running_send ]]
-        then
-            echo "Backup already in progress"
-        else
-            attempt_extern_backup
-        fi
+        attempt_extern_backup
     else
-        snapshot $config $SUBVOLUME "${LOCAL_SNAPSHOT_MOUNT}" 
-        prune $config "${LOCAL_SNAPSHOT_MOUNT}"
-#        echo "$SUBVOLUMES" | prune "${LOCAL_SNAPSHOT_MOUNT}"
-    #    if [[ test_running_send ]]
-    #    then
-    #        echo "Backup already in progress"
-    #    else
-    #        attempt_extern_backup
-    #    fi
+        snapshot
+        prune
+        attempt_extern_backup
     fi
 done
 
